cafetariaproject/cafeadmin/urls.py
from django.urls import path

from .views import (home_view, categories_view, add_category_view, delete_category_view,
                    update_category_view, category_fooditem_view, add_fooditem_view,
                    delete_fooditem_view, update_fooditem_view, dinning_table_view,
                    add_dinningtable_view, update_dinningtable_view, delete_dinningtable_view,
                    orders_view, confirm_orders_view, reviews_view)

app_name = 'cafeadmin'

urlpatterns = [
    path("", home_view, name="home"),
    path("reviews/", reviews_view, name="reviews"),
    path("orders/", orders_view, name="customer-orders"),
    path("confirm-order/<int:order_id>/", confirm_orders_view, name="confirm-order"),
    path("categories/", categories_view, name="categories"),
    path("add_category/", add_category_view, name="add-category"),
    path("delete_category/<int:category_id>/", delete_category_view, name="delete-category"),
    path("update_category/<int:category_id>/", update_category_view, name="update-category"),
    path("category/<int:category_id>/fooditems/", category_fooditem_view, name="category-items"),
    path("add_fooditem/<int:category_id>/", add_fooditem_view, name="add-fooditem"),
    path("delete_fooditem/<int:fooditem_id>/<int:category_id>/", delete_fooditem_view, name="delete-fooditem"),
    path("update_fooditem/<int:fooditem_id>/<int:category_id>/", update_fooditem_view, name="update-fooditem"),
    path("dinningtables/", dinning_table_view, name="dinningtables"),
    path("add_dinningtable/", add_dinningtable_view, name="add-dinning-table"),
    path("delete_dinningtable/<int:table_id>/", delete_dinningtable_view, name="delete-dinning-table"),
    path("update_dinningtable/<int:table_id>/", update_dinningtable_view, name="update-dinning-table"),
]   

cafetariaproject/cafetariaproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #admin site
    path("admin/", admin.site.urls),

    #authentication
    path("account/", include('django.contrib.auth.urls')),

    path("account/", include('myapps.account.urls')),

    #entrypoint
    path("", include('myapps.cafetaria.urls')),
    path("cafeadmin/", include('cafeadmin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafetariaproject/myapps/cafetaria/urls.py
from django.urls import path

from .views import (home_view, handle_unauthorized_access, addtocart_view, cart_view, 
                    food_items_view,checkout_view, order_complete_view, increase_orderitem_view,
                    decrease_orderitem_view, remove_item_view, order_history_view, order_receipt_view,
                    review_dish_view, food_detail_view, customer_points_view, customer_notifications_view,
                    marknotification_read_view)

app_name="cafetaria"

urlpatterns=[
    path("", home_view, name="home"),
    path("notifications/", customer_notifications_view, name="notifications"),
    path("mark-as-read/<int:notification_id>/", marknotification_read_view, name="mark-read"),
    path("points/", customer_points_view, name="points"),
    path("addtocart/<int:food_id>/", addtocart_view, name="addtocart"),
    path("food/", food_items_view, name="food"),
    path("food-detail/<int:food_id>/", food_detail_view, name="food-detail"),
    path("cart/", cart_view, name="cart"),
    path("order-history/", order_history_view, name="order-history"),
    path("order-review/<int:order_id>/", review_dish_view, name="review-order"),
    path("order-receipt/<int:order_id>/", order_receipt_view, name="order-reciept"),
    path("increase-order/<int:item_id>/", increase_orderitem_view, name="increase-quantity"),
    path("decrease-order/<int:item_id>/", decrease_orderitem_view, name="decrease-quantity"),
    path("remove-item/<int:item_id>/", remove_item_view, name="remove-item"),
    path("checkout/", checkout_view, name="checkout"),
    path("order-complete/<int:order_id>/", order_complete_view, name="order-complete"),
    path("unauthorized/", handle_unauthorized_access, name="handle_unauthorized_access"),
]

cafetariaproject/myapps/cafetaria/forms.py
from django import forms

from .models import UserDinningTable, Review

class UserDinningForm(forms.ModelForm):
    class Meta:
        model = UserDinningTable
        fields = ["dinning_table"]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["rating", "comment"]
        widgets = {
            'rating': forms.RadioSelect(choices=[(i, str(i)) for i in range(1, 6)]),
            'comment': forms.Textarea(attrs={'rows': 3}),
        }

cafetariaproject/myapps/cafetaria/views.py
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404, HttpResponse
from django.contrib.auth.decorators import user_passes_test

from .models import (Category, FoodItem, Order, OrderItem, UserDinningTable, 
                     Review, CustomerPoint, Notification)
from .forms import UserDinningForm, ReviewForm
from .myutils import (calculate_total_price,calculate_total_item_price, 
                      increase_orderitem_quantity, decrease_orderitem_quantity, 
                      assign_points)


#  defines a role based  redirect function for customers
def is_customer(user):
    if user.is_authenticated and user.role == 'customer':
        return True
    if user.is_authenticated and user.role == 'admin':
        return False
    return False

# Custom view to handle unauthorized access for both roles
def handle_unauthorized_access(request):

    """
    Redirect logged-in users to their respective homepages if they are
    already authenticated but trying to access an unauthorized view.
    """
    
    user = request.user
    if user.role == 'customer':
        return redirect('cafetaria:home')
    elif user.role == 'admin':
        return redirect('cafeadmin:home')
    else:
        return redirect('login')
    
@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def home_view(request):

    """
    Renders the home page for authenticated users.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: The rendered home page.
    """
    user = request.user

    user_dinning_table, created = UserDinningTable.objects.get_or_create(user=user)

    if request.method == 'POST':
        form = UserDinningForm(request.POST, instance=user_dinning_table)

        if form.is_valid:
            form.save()
            return redirect("cafetaria:food")
    else:
        form = UserDinningForm(instance=user_dinning_table)

    context = {
        "form": form,
    }
    return render(request, "cafetaria/home.html", context)


@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def food_items_view(request):

    categories = Category.objects.all()
    

    context = {
        "categories":categories,
        
    }
    return render(request, "cafetaria/food_items.html", context)



@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def food_detail_view(request, food_id):

    food = get_object_or_404(FoodItem, id=food_id)
    

    context = {
        "food":food,
        
    }
    return render(request, "cafetaria/food_detail.html", context)

@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def addtocart_view(request, food_id):
    user = request.user

    food_item = get_object_or_404(FoodItem, id=food_id)

    order, created = Order.objects.get_or_create(user=user, is_paid = False)
    
    order_item, created = OrderItem.objects.get_or_create(order=order, fooditem=food_item)

    total_price = calculate_total_price(order)
    order.total_price = total_price
    order.save()

    orderitem_total_price = calculate_total_item_price(order_item)
    order_item.total_price = orderitem_total_price
    order_item.save()


    return redirect("cafetaria:food")

@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def cart_view(request):

    user = request.user
    
    try:
        order = Order.objects.get(user=user, is_paid=False)
    except Order.DoesNotExist:
        order = None

    if order is None:
        pass
    
    else:
        total_price = calculate_total_price(order)
        order.total_price = total_price
        order.save()

        for order_item in order.orderitems.all():
            orderitem_total_price = calculate_total_item_price(order_item)
            order_item.total_price = orderitem_total_price
            order_item.save()
    
    context = {
        'order': order,
        }
    
    return render(request, "cafetaria/cart.html", context)


@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def checkout_view(request):
    user=request.user
    order = get_object_or_404(Order, user=user, is_paid=False)

    # processs payment here

    order.is_paid = True 
    order.save()

    # assign points to customer
    transaction = assign_points(order)

    
    user_dinning = UserDinningTable.objects.get(user = user)
    table = user_dinning.dinning_table.table_number

    # reset the user dinning table to None after order is delivered
    # user_dinning.dinning_table = None
    # user_dinning.save()

    

    return redirect("cafetaria:order-complete", order.id)

@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def order_complete_view(request, order_id):

    user = request.user
    order = get_object_or_404(Order, id=order_id)

    if user != order.user:
        return HttpResponse("Sorry, you are not allowed to access this content.")

    context = {
        "order": order
    }

    return render(request, 'cafetaria/order_complete.html', context)


@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def increase_orderitem_view(request, item_id):

    orderitem = get_object_or_404(OrderItem, id=item_id)
    orderitem = increase_orderitem_quantity(orderitem)

    return redirect("cafetaria:cart")


@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def decrease_orderitem_view(request, item_id):

    orderitem = get_object_or_404(OrderItem, id=item_id)
    orderitem = decrease_orderitem_quantity(orderitem)

    return redirect("cafetaria:cart")


@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def remove_item_view(request, item_id):

    orderitem = get_object_or_404(OrderItem, id=item_id)
    order = orderitem.order
    orderitem.delete()

    if order.orderitems.count() == 0:
        order.delete()
    
    return redirect("cafetaria:cart")


@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def order_history_view(request):
    user = request.user

    try:
        past_orders = get_list_or_404(Order, user=user, is_paid=True, status="COMPLETE")
    except:
        past_orders = None


    try:
        p_order = get_list_or_404(Order, user=user, is_paid=True, status="PENDING")
    except:
        p_order = None

    context = {
        "past_orders":past_orders,
        "p_order": p_order,
    }

    return render(request, 'cafetaria/order_history.html', context)

@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def order_receipt_view(request, order_id):
    order = get_object_or_404(Order, id = order_id)

    context = {
        "order":order,
    }

    return render(request, 'cafetaria/order_reciept.html', context)


@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def review_dish_view(request, order_id):
    user = request.user
    order = get_object_or_404(Order, id=order_id)

    if user != order.user:
        return HttpResponse("Sorry, you are not allowed to access this content.")
    

    # Ensure that the order was placed today
    if order.created_at.date() != timezone.now().date():
        messages.error(request, "You can only review meals on the same day you ordered them.")
        return redirect('cafetaria:order-history')
    
    # Check if a review already exists for this food item and order
    if Review.objects.filter(user=request.user, order=order).exists():
        messages.error(request, "You have already reviewed this item.")
        return redirect('cafetaria:order-history')

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        
        if form.is_valid():
            review = form.save(commit=False)
            review.user = user
            review.order = order
            review.save()
            return redirect("cafetaria:order-history")
    
    else:
        form = ReviewForm()
    
    context = {
        "form":form,
        "order":order,
    }

    return render(request, 'cafetaria/review_order.html', context)

@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def customer_points_view(request):
    user = request.user

    try:
        customer_points = get_object_or_404(CustomerPoint, user=user)
        points = customer_points.points
    except CustomerPoint.DoesNotExist:
        points = 0

    context = {
        "points":points,
    }

    return render(request, 'cafetaria/customer_points.html', context)

@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def customer_notifications_view(request):
    notifications = get_list_or_404(Notification, user=request.user)


    context = {
        "notifications":notifications,
    }

    return render(request, 'cafetaria/notifications.html', context)

@login_required
@user_passes_test(is_customer, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def marknotification_read_view(request, notification_id):

    notification = get_object_or_404(Notification,id=notification_id)

cafetariaproject/myapps/cafetaria/templates/cafetaria/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}| Cafetaria</title>
</head>
<body>
   <main>
    <nav>
        <ul>
            <li>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <a href=""><button type="submit">LOGOUT</button></a>
                </form>
            </li>
            <li>
                <a href="{% url 'cafetaria:food' %}">Menu </a>
            </li>
            <li>
                <a href="{% url 'cafetaria:home' %}">Dinning Table </a>
            </li>
            <li>
                <a href="">Special Offers </a>
            </li>
            <li>
                <a href="{% url 'cafetaria:notifications' %}">Notifications({{notification}}) </a>
            </li>
            <li>
                <a href="{% url 'cafetaria:cart' %}">Cart({{cart_item_count}})</a>
            </li>
            <li>
                <a href="{% url 'cafetaria:order-history' %}">Orders</a>
            </li>
            <li>
                <a href="{% url 'cafetaria:points' %}">Customer Points </a>
            </li>
        </ul>
    </nav>
    {% block content %}
    {% endblock content %}

   </main>

    <footer>
        <p>&copy; 2024 XXX.Cafeteria </p>
    </footer>
</body>

</html>

cafetariaproject/myapps/cafetaria/templates/cafetaria/cart.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Order Summary{% endblock title %}

{% block content %}
<section>
    <h3>Your Cart:</h3>
    {% if order %}
    <h3>
        {{order}}
    </h3>
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.orderitems.all %}
            <tr>
                <td>{{ item.fooditem.name }}</td>
                <td>@{{ item.fooditem.price }}</td>
                <td>
                    <button><a href="{% url 'cafetaria:increase-quantity' item.id %}">+</a></button> {{item.quantity}}<button><a href="{% url 'cafetaria:decrease-quantity' item.id %}">-</a></button>
                </td>
                <td>{{item.total_price}}</td>
                <td><button><a href="{% url 'cafetaria:remove-item' item.id %}">REMOVE</a></button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  
    <h4>Total Price: Ksh.{{order.total_price}}</h4>
    <button type="button"><a href="{% url 'cafetaria:checkout' %}">CheckOut</a></button>
    {% else %}
    <p>You have no items in Cart.</p>
    {% endif %}
</section>

{% endblock content %}

cafetariaproject/myapps/cafetaria/templates/cafetaria/customer_points.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Customer Points{% endblock title %}

{% block content %}
<section>
    
    <h2>Points: {{points}}</h2>
    <h4>Redeem Points? </h4>
    
</section>
{% endblock content %}

cafetariaproject/myapps/cafetaria/templates/cafetaria/food_detail.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Food Detail{% endblock title %}

{% block content %}
<section>
    
    <h2>Food Detail</h2>
    <div>
        <h4> {{food.name}} | Ksh.{{food.price}}</h4>
        <p>{{food.description}}</p>
        <p><span><a href="{% url 'cafetaria:addtocart' food.id %}#food-item-{{food.id}}">Add To Cart</a></span></p>
        
        <img src="{{food.image.url}}" alt="" height="100" width="200">
        
    </div>
    
</section>
{% endblock content %}

cafetariaproject/myapps/cafetaria/templates/cafetaria/food_items.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Home{% endblock title %}

{% block content %}
<section>
    <p>Current dining table: Table {{user.userdinningtable.dinning_table.table_number}}</p>
    <form method="get">
        <input type="search" placeholder="search food..." name="q">
        <button type="submit">Search</button>
    </form>
    <h2>Available Food </h2>
    {% for category in categories %}
        <h3>{{category.name}}</h3>
        {% for food in category.fooditems.all %}
            {% if food.is_available %}
            <ul>
                <li id="food-item-{{food.id}}">
                    <div>
                        <h4> <a href="{% url 'cafetaria:food-detail' food.id %}">{{food.name}}</a> | Ksh.{{food.price}}</h4>
                        <p>{{food.description}}</p>
                        <p><span><a href="{% url 'cafetaria:addtocart' food.id %}#food-item-{{food.id}}">Add To Cart</a></span></p>
                        
                        <img src="{{food.image.url}}" alt="" height="100" width="200">
                        
                    </div>
                </li>
            </ul>
            {% endif %}
        {% empty %}
        <p>No food item in category</p>
        {% endfor %}
    {% empty %}
    <p>No food Items Available Today. Sorry!</p>
    {% endfor %}
</section>
{% endblock content %}

cafetariaproject/myapps/cafetaria/templates/cafetaria/home.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Home{% endblock title %}

{% block content %}
<section>
    <h3>Welcome Home {{user}}</h3>
    <h2>What table are you dinning at?</h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
</section>
{% endblock content %}

cafetariaproject/myapps/cafetaria/templates/cafetaria/notifications.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Notifications{% endblock title %}

{% block content %}
<section>
    
    <h2>Notifications</h2>
    {% if notifications %}
        <ul>
        {% for notification in notifications %}
            <p>{{notification.created_at}}</p>
            <li>{{notification.message}} {% if notification.is_read%} {% else %} <a href="{% url 'cafetaria:mark-read' notification.id  %}">Mark as Read</a> {% endif %}</li>
        {% endfor %}
        </ul>
    {% else %}
    <p>You have no notifications</p>
    {% endif %}
    
</section>
{% endblock content %}

cafetariaproject/myapps/cafetaria/templates/cafetaria/order_complete.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Home{% endblock title %}

{% block content %}
<section>
    <h2>Order Confirmation</h2>

    <p>Thank you. Order received.Your order number is:  {{ order }}.</p>
    <h5>Order is being processed.</h5>

    <a href="">Download Reciept</a>
    <a href="{% url 'cafetaria:order-reciept' order.id %}">View Reciept</a>
    
</section>
{% endblock content %}

cafetariaproject/myapps/cafetaria/templates/cafetaria/order_history.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Order History{% endblock title %}

{% block content %}
<section>
    <h2>Pending Order</h2>
    <table>
        <tr>
            <th>OrderId</th>
            <th>Customer</th>
            <th>Total Price</th>
            <th>Is Paid</th>
            <th>Estimated Delivery Time</th>
            <th>Status</th>
        </tr>
        {% if p_order %}
            {% for order in p_order %}
            <tr>
                <td>#{{order.id}}</td>
                <td>{{order.user.username}}</td>
                <td>{{order.total_price}}</td>
                <td>{{order.is_paid}}</td>
                <td>{{order.estimated_time}}</td>
                <td>{{order.status}}</td>
            </tr>
            {% endfor %}
        {% else %}
        <tr>
            <td colspan="6">No Pending Order.</td>
         
        </tr>
        {% endif %}
    </table>
    
</section>
<section>
    {% if messages%}
        {% for message in messages%}
        <p>{{message}}</p>
        {% endfor%}
    {% endif %}
    <h2>Past Orders:</h2>
    {% if past_orders %}
    <ul>
        {% for order in past_orders %}
            <li>
                <h4>Date: {{ order.created_at }}</h4>
                <strong>Order #{{ order}} - KSh {{ order.total_price }}</strong>
                <ul>
                    {% for item in order.orderitems.all %}
                        <li>{{ item.quantity }} x {{ item.fooditem.name }} - @KSh {{ item.fooditem.price }}</li>
                    {% endfor %}
                </ul>
                <p>Paid: {{ order.is_paid }}</p>
                <a href="{% url 'cafetaria:order-reciept' order.id %}">View Reciept</a> | 
                <a href="{% url 'cafetaria:review-order' order.id %}">Review Dish</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>You have no past orders.</p>
    {% endif %}

</section>
{% endblock content %}

cafetariaproject/myapps/cafetaria/templates/cafetaria/order_reciept.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Receipt for Order #{{order}}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        h2 {
            color: #333;
        }
        .order-details {
            margin-top: 20px;
        }
        .order-details ul {
            list-style-type: none;
            padding: 0;
        }
        .order-details ul li {
            margin-bottom: 10px;
        }
        .order-total {
            font-weight: bold;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h2>Thank you for your order!</h2>
    <p>Dear {{ order.user.username }},</p>
    <p>We are pleased to inform you that your payment for order #{{ order.id }} has been confirmed.</p>
    <p>The Order will be ready in {{order.estimated_time}} minutes.</p>

    <h3 class="order-details" >Order Summary</h3>
    <p>Date: {{ order.created_at|date:"F j, Y, g:i a" }}</p>
    <ul>
        {% for item in order.orderitems.all %}
            <li>{{ item.quantity }} x {{ item.fooditem.name }} - @KSh {{ item.fooditem.price }}</li>
        {% endfor %}
    </ul>

    <div class="order-total">
        <p>Total: KSh {{ order.total_price }}</p>
        
    </div>
    
    <p>Thank you for dining with us!</p>
    <p>Best regards,<br>The Cafeteria Team</p>
</body>
</html>

cafetariaproject/myapps/cafetaria/templates/cafetaria/review_order.html
{% extends 'cafetaria/_base.html' %}
{% block title %}Review Order{% endblock title %}

{% block content %}
<section>
    <h2>Review #{{order}}</h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
</section>
{% endblock content %}