cafetariaproject/cafeadmin/urls.py
from django.urls import path

from .views import (home_view, categories_view, add_category_view, delete_category_view,
                    update_category_view, category_fooditem_view, add_fooditem_view,
                    delete_fooditem_view, update_fooditem_view, dinning_table_view,
                    add_dinningtable_view, update_dinningtable_view, delete_dinningtable_view,
                    orders_view, confirm_orders_view, reviews_view)

app_name = 'cafeadmin'

urlpatterns = [
    path("", home_view, name="home"),
    path("reviews/", reviews_view, name="reviews"),
    path("orders/", orders_view, name="customer-orders"),
    path("confirm-order/<int:order_id>/", confirm_orders_view, name="confirm-order"),
    path("categories/", categories_view, name="categories"),
    path("add_category/", add_category_view, name="add-category"),
    path("delete_category/<int:category_id>/", delete_category_view, name="delete-category"),
    path("update_category/<int:category_id>/", update_category_view, name="update-category"),
    path("category/<int:category_id>/fooditems/", category_fooditem_view, name="category-items"),
    path("add_fooditem/<int:category_id>/", add_fooditem_view, name="add-fooditem"),
    path("delete_fooditem/<int:fooditem_id>/<int:category_id>/", delete_fooditem_view, name="delete-fooditem"),
    path("update_fooditem/<int:fooditem_id>/<int:category_id>/", update_fooditem_view, name="update-fooditem"),
    path("dinningtables/", dinning_table_view, name="dinningtables"),
    path("add_dinningtable/", add_dinningtable_view, name="add-dinning-table"),
    path("delete_dinningtable/<int:table_id>/", delete_dinningtable_view, name="delete-dinning-table"),
    path("update_dinningtable/<int:table_id>/", update_dinningtable_view, name="update-dinning-table"),
]   

cafetariaproject/cafetariaproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #admin site
    path("admin/", admin.site.urls),

    #authentication
    path("account/", include('django.contrib.auth.urls')),

    path("account/", include('myapps.account.urls')),

    #entrypoint
    path("", include('myapps.cafetaria.urls')),
    path("cafeadmin/", include('cafeadmin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafetariaproject/cafeadmin/models.py
from django.db import models

# Create your models here.

cafetariaproject/cafeadmin/forms.py
from django import forms
from myapps.cafetaria.models import Category, FoodItem, DiningTable, Order


class CategoryForm(forms.ModelForm):

    """
    CategoryForm for adding new categories.
    """
    class Meta:
        model = Category
        fields = '__all__'



class FoodItemForm(forms.ModelForm):

    """
    FoodItemForm for adding new fooditem.
    """
    class Meta:
        model = FoodItem
        fields = [
            "name",
            "description",
            "price",
            "image",
            "is_available",
        ]
    

class DinningTableForm(forms.ModelForm):

    """
    DinningTableForm for adding new dinningtables.
    """
    class Meta:
        model = DiningTable
        fields = [
            "table_number",
        ]

class UpdateOrderForm(forms.ModelForm):
    """
    OrderForm for updating an order.
    """

    class Meta:
        model = Order
        fields = [
            "estimated_time",
            "status",
        ]

cafetariaproject/cafeadmin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import user_passes_test, login_required
from django.db.models import Q
from django.contrib import messages

from myapps.cafetaria.models import Category, FoodItem, DiningTable, Order, Review, Notification

from .forms import CategoryForm, FoodItemForm, DinningTableForm, UpdateOrderForm


#  Define a role-based redirect function for cafeteria admins
def is_cafe_admin(user):
    if user.is_authenticated and user.role == 'admin':
        return True
    if user.is_authenticated and user.role == 'customer':
        return False
    return False


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def home_view(request):
    return render(request, 'cafeadmin/home.html')


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def categories_view(request):

    """
    Handles the categories page.
    """
    # query value from the search input
    q = request.GET.get("q")

    # filtering the categories objects based on the q value
    categories = Category.objects.filter(Q(name__icontains=q)) if q else Category.objects.all()

    context = {
        "categories": categories,
    }

    return render(request, "cafeadmin/food_categories.html", context)

@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def add_category_view(request):

    """
    Handles the adding a new category.
    """
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect("cafeadmin:categories")
    else:
        form = CategoryForm()

    context = {
        "form":form,
    }
    return render(request,"cafeadmin/add_category.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def delete_category_view(request, category_id):

    """
    Handles deleting a category.
    """

    category = get_object_or_404(Category, id = category_id)
    category_name = category.name

    if request.method == 'POST':
        category.delete()
        # include the logic for a success message
        messages.success(request, f'Successfully deleted {category_name}')
        return redirect("cafeadmin:categories")

    context = {
        "category":category,
    }
    return render(request,"cafeadmin/delete_category.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def update_category_view(request, category_id):

    """
    Handles the updating a new category.
    """

    category = get_object_or_404(Category, id = category_id)

    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        
        if form.is_valid():
            form.save()
            return redirect("cafeadmin:categories")
    else:
        form = CategoryForm(instance=category)

    context = {
        "form":form,
        "category":category,
    }

    return render(request,"cafeadmin/update_category.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def category_fooditem_view(request, category_id):

    """
    Handles the categories page.
    """
    # query value from the search input
    q = request.GET.get("q")
    category = get_object_or_404(Category, id=category_id)

    # filtering the categories objects based on the q value
    fooditems = FoodItem.objects.filter(Q(name__icontains=q),category=category) if q else FoodItem.objects.filter(category=category)

    context = {
        "category": category,
        "fooditems": fooditems,
    }

    return render(request, "cafeadmin/category_items.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def add_fooditem_view(request, category_id):

    """
    Handles the adding a new fooditem.
    """
    category = get_object_or_404(Category, id = category_id)

    if request.method == 'POST':
        form = FoodItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            food = form.save(commit=False)
            food.category = category
            food.save()
            return redirect("cafeadmin:category-items", category_id)
    else:
        form = FoodItemForm()

    context = {
        "form":form,
    }
    return render(request,"cafeadmin/add_fooditem.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def delete_fooditem_view(request, fooditem_id, category_id):

    """
    Handles deleting a fooditem.
    """

    fooditem = get_object_or_404(FoodItem, id = fooditem_id)
    category = get_object_or_404(Category, id = category_id)

    if request.method == 'POST':
        fooditem.delete()
        return redirect("cafeadmin:category-items", category_id)

    context = {
        "fooditem":fooditem,
        "category": category,
    }
    return render(request,"cafeadmin/delete_fooditem.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def update_fooditem_view(request, fooditem_id, category_id):

    """
    Handles updating a fooditem.
    """

    fooditem = get_object_or_404(FoodItem, id = fooditem_id)

    if request.method == 'POST':
        form = FoodItemForm(request.POST, request.FILES, instance=fooditem)
        
        if form.is_valid():
            form.save()
            return redirect("cafeadmin:category-items", category_id)
    else:
        form = FoodItemForm(instance=fooditem)

    context = {
        "form":form,
        "fooditem":fooditem,
    }

    return render(request,"cafeadmin/update_fooditem.html", context)



@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def dinning_table_view(request):

    """
    Handles the dinning table page.
    """
    # query value from the search input
    q = request.GET.get("q")

    # filtering the categories objects based on the q value
    tables = DiningTable.objects.filter(Q(table_number__icontains=q)) if q else DiningTable.objects.all()

    context = {
        "tables": tables,
    }

    return render(request, "cafeadmin/dinning_tables.html", context)

@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def add_dinningtable_view(request):

    """
    Handles the adding of a new dinningtable.
    """
    if request.method == 'POST':
        form = DinningTableForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect("cafeadmin:dinningtables")
    else:
        form = DinningTableForm()

    context = {
        "form":form,
    }
    return render(request,"cafeadmin/add_dinning_table.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def delete_dinningtable_view(request, table_id):

    """
    Handles deleting a dinningtable.
    """

    table = get_object_or_404(DiningTable, id = table_id)

    if request.method == 'POST':
        table.delete()
        
        return redirect("cafeadmin:dinningtables")

    context = {
        "table":table,
    }
    return render(request,"cafeadmin/delete_dinning_table.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def update_dinningtable_view(request, table_id):

    """
    Handles the updating a dinningtable.
    """

    table = get_object_or_404(DiningTable, id = table_id)

    if request.method == 'POST':
        form = DinningTableForm(request.POST, instance=table)
        
        if form.is_valid():
            form.save()
            return redirect("cafeadmin:dinningtables")
    else:
        form = DinningTableForm(instance=table)

    context = {
        "form":form,
        "table":table,
    }

    return render(request,"cafeadmin/update_dinning_table.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def orders_view(request):
    
    paid_orders = Order.objects.filter(is_paid = True, status = "PENDING")
    unpaid_orders = Order.objects.filter(is_paid = False, status = "PENDING")
    complete_paid_orders = Order.objects.filter(is_paid = True, status = "COMPLETE")

    context = {
        "paid_orders": paid_orders,
        "unpaid_orders": unpaid_orders,
        "complete_paid_orders": complete_paid_orders,
    }

    return render(request,"cafeadmin/customer_orders.html", context)


@login_required
@user_passes_test(is_cafe_admin, login_url='cafetaria:handle_unauthorized_access', redirect_field_name=None)
def confirm_orders_view(request, order_id):

    order = get_object_or_404(Order, id=order_id)
    
    if request.method == 'POST':
        form = UpdateOrderForm(request.POST, instance=order)
        
        if form.is_valid():
            form.save()

            # sends notification to user
            if order.status == 'COMPLETE':
                message = f"Your order # {order.id} has been confirmed. "
                notification = Notification.objects.create(user=order.user,message=message)
            return redirect("cafeadmin:customer-orders")
    else:
        form= UpdateOrderForm(instance=order)

    context = {
        "form":form,
        "order": order,
    }

cafetariaproject/cafeadmin/templates/cafeadmin/add_category.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Add Category{% endblock title %}

{% block content %}
<section>
    <h3>Add New Food Category</h3>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">ADD</button>
    </form>
</section>
{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/add_dinning_table.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Add Dinning Table{% endblock title %}

{% block content %}
<section>
    <h3>Add Dinning Table</h3>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">ADD</button>
    </form>
</section>
{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/add_fooditem.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Add FoodItem{% endblock title %}

{% block content %}
<section>
    <h3>Add New Food Item</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">ADD</button>
    </form>
</section>
{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/category_items.html
{% extends 'cafeadmin/_base.html' %}

{% block title %}Food Items{% endblock title %}

{% block content %}
<section>
    <h2>{{category.name}}</h2>
    <p>{{category.description}}</p>

    <ul>
        <li>
            <a href="{% url 'cafeadmin:add-fooditem' category.id %}">Add Food item to Category</a>
        </li>
    </ul>
    <form method="get">
        <input type="search" placeholder="search food..." name="q">
        <button type="submit">Search</button>
    </form>

    <h4>Food Items in Category: {{category.name}}</h4>
    
    <table>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
        {% for fooditem in fooditems %}
        <tr>
            <td style="font-weight: bold;">{{fooditem.name}}</td>
            <td>{{fooditem.description|truncatewords:5}}</td>
            <td>ksh.{{fooditem.price}}</td>
            <td><span><button><a href="{% url 'cafeadmin:delete-fooditem' fooditem.id category.id %}">DELETE</a></button> | <button><a href="{% url 'cafeadmin:update-fooditem' fooditem.id category.id %}">UPDATE</a></button></span></td>
        </tr>
        {% empty %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
    </table>
    
</section>

{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/confirm_orders.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Confirm Orders{% endblock title %}

{% block content %}
<section>
    <h3>#{{order}}</h3>
    <h5>Order Items:</h5>
    <ul>
        {% for item in order.orderitems.all%}
        <li>{{item.fooditem.name}}</li>
        {% endfor %}
    </ul>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">UPDATE</button>
    </form>
    <p><a href="">Print Receipt</a></p>
</section>
{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/customer_orders.html
{% extends 'cafeadmin/_base.html' %}

{% block title %}Orders{% endblock title %}

{% block content %}
<section>
    <h2>Paid Orders</h2>
    
    <table>
        <tr>
            <th>OrderId</th>
            <th>Total Price</th>
            <th>Is Paid</th>
            <th>Estimated Time</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        {% for order in paid_orders %}
        <tr>
            <td>#{{order}}</td>
            <td>{{order.total_price}}</td>
            <td>{{order.is_paid}}</td>
            <td>{{order.estimated_time}}</td>
            <td>{{order.status}}</td>
            <td><span><button><a href="{% url 'cafeadmin:confirm-order' order.id %}">UPDATE ORDER</a></button></span></td>
        </tr>
        {% empty %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
    </table>
    
</section>

<section>
    <h2>Complete Orders</h2>
    
    <table>
        <tr>
            <th>OrderId</th>
            <th>Total Price</th>
            <th>Is Paid</th>
            <th>Estimated Time</th>
            <th>Status</th>
        </tr>
        {% for order in complete_paid_orders %}
        <tr>
            <td>#{{order}}</td>
            <td>{{order.total_price}}</td>
            <td>{{order.is_paid}}</td>
            <td>{{order.estimated_time}}</td>
            <td>{{order.status}}</td>
        </tr>
        {% empty %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
    </table>
    
</section>

<section>
    <h2>UnPaid Orders</h2>
    
    <table>
        <tr>
            <th>OrderId</th>
            <th>Total Price</th>
            <th>Is Paid</th>
            <th>Estimated Time</th>
            <th>Status</th>

            
        </tr>
        {% for order in unpaid_orders %}
        <tr>
            <td>#{{order}}</td>
            <td>{{order.user.username}}</td>
            <td>{{order.total_price}}</td>
            <td>{{order.is_paid}}</td>
            <td>{{order.estimated_time}}</td>
            <td>{{order.status}}</td>
        </tr>
        {% empty %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            
        </tr>
        {% endfor %}
    </table>
    
</section>

{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/delete_category.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Delete Category{% endblock title %}

{% block content %}
<section>
    <h3>Are you sure you want to delete Category: "{{category.name}}"</h3>
    <h4>WARNING!!!</h4>
    <p>Deleting a food category deletes all food items under it.</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">DELETE</button>
        <button><a href="{% url 'cafeadmin:categories' %}">CANCEL</a></button>
    </form>
</section>
{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/delete_dinning_table.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Delete Dinning Table{% endblock title %}

{% block content %}
<section>
    <h3>Are you sure you want to delete Table: "{{table.table_number}}"</h3>
    <form method="post">
        {% csrf_token %}
        <button type="submit">DELETE</button>
        <button><a href="{% url 'cafeadmin:dinningtables' %}">CANCEL</a></button>
    </form>
</section>
{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/delete_fooditem.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Delete FoodItem{% endblock title %}

{% block content %}
<section>
    <h3>Are you sure you want to delete Fooditem: "{{fooditem.name}}"</h3>
    <h4>WARNING!!!</h4>
    <p>Deleting a fooditem deletes it from the related category.</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">DELETE</button>
        <button><a href="{% url 'cafeadmin:category-items' category.id %}">CANCEL</a></button>
    </form>
</section>
{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/food_categories.html
{% extends 'cafeadmin/_base.html' %}

{% block title %}Food Categories{% endblock title %}

{% block content %}
<section>
    <h2>Food Categories</h2>

    <ul>
        <li>
            <a href="{% url 'cafeadmin:add-category' %}">Add Category</a>
        </li>
    </ul>
    <form method="get">
        <input type="search" placeholder="search category..." name="q">
        <button type="submit">Search</button>
    </form>

    <h4>All Categories</h4>
    
    <table>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
        {% for category in categories %}
        <tr>
            <td><a href="{% url 'cafeadmin:category-items' category.id %}">{{category.name}}</a></td>
            <td>{{category.description|truncatewords:10}}</td>
            <td><span><button><a href="{% url 'cafeadmin:delete-category' category.id %}">DELETE</a></button> | <button><a href="{% url 'cafeadmin:update-category' category.id %}">UPDATE</a></button></span></td>
        </tr>
        {% empty %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
    </table>
    
</section>

{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/home.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Dashboard{% endblock title %}

{% block content %}
<section>
    <h2>Hello {{user}}, Welcome to Admins dashboard.</h2>
    <h3>Statistics</h3>
    <p>Food Categories: </p>
    <p>Food items: </p>
    <p>Todays Orders: </p>
    <p>Todays Reviews: </p>
    <p>Dinning Tables: </p>
</section>

{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/reviews.html
{% extends 'cafeadmin/_base.html' %}

{% block title %}Order Reviews{% endblock title %}

{% block content %}
<section>
    <h2>Order Reviews</h2>
    <table>
        <tr>
            <th>Order</th>
            <th>Rating</th>
            <th>Comment</th>
            <th>Food item</th>
        </tr>
        {% for review in reviews %}
        <tr>
           <td>{{review.order}}</td>
           <td>{{review.rating}}</td>
           <td>{{review.comment}}</td>
           <td>
            <ul>
            {% for item in review.order.orderitems.all %}
                <li>{{item.fooditem.name}}</li>
            {% endfor %}
            </ul>
           </td>
        </tr>
        {% empty %}
        <tr>
            <td>No Reviews</td>
            
        </tr>
        {% endfor %}
    </table>
    
</section>

{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/update_category.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Update Category{% endblock title %}

{% block content %}
<section>
    <h3>Update {{category.name}}</h3>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">UPDATE</button>
    </form>
</section>
{% endblock content %}

cafetariaproject/cafeadmin/templates/cafeadmin/update_fooditem.html
{% extends 'cafeadmin/_base.html' %}

{% block title %} Update Fooditem{% endblock title %}

{% block content %}
<section>
    <h3>Update {{fooditem.name}}</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">UPDATE</button>
    </form>
</section>
{% endblock content %}